# Use official Node.js image as base image
FROM node:16-slim

# Set working directory inside container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port on which the app will run
EXPOSE 3000

# Command to start the frontend application
CMD ["npm", "start"]
